#!/usr/bin/env bash

set -euo pipefail

readonly WHISPER_REPOSITORY="https://github.com/ggml-org/whisper.cpp.git"
readonly WHISPER_TAG="v1.9.2"
readonly WHISPER_COMMIT="306c88f4d1286aec1bf96e544632897886af5501"
readonly DEPLOYMENT_TARGET="15.0"

usage() {
    echo "Usage: $0 OUTPUT_DIRECTORY [SOURCE_REPOSITORY]" >&2
    echo "Builds whisper-v1.9.2-metal-macos.xcframework.zip in a new output directory." >&2
}

if [[ $# -lt 1 || $# -gt 2 ]]; then
    usage
    exit 64
fi

output_directory=$1
source_repository=${2:-$WHISPER_REPOSITORY}
if [[ -e "$output_directory" ]]; then
    echo "error: output path already exists: $output_directory" >&2
    exit 73
fi

script_directory=$(cd "$(dirname "$0")" && pwd)
repository_root=$(cd "$script_directory/.." && pwd)
patch_path="$repository_root/third_party/whisper.cpp/198-metal-warnings.patch"
if [[ ! -f "$patch_path" ]]; then
    echo "error: patch not found: $patch_path" >&2
    exit 66
fi

for tool in cmake git lipo shasum swift unzip xcodebuild xcrun zip; do
    if ! command -v "$tool" >/dev/null; then
        echo "error: required tool not found: $tool" >&2
        exit 69
    fi
done

# Source paths are present in upstream assertion strings, so use one stable build root. This also
# makes archive checksums comparable across clean runs on the same Xcode/toolchain version.
working_directory="/tmp/voxflow-whisper-v1.9.2-reproducible"
if [[ -e "$working_directory" ]]; then
    echo "error: build path already exists: $working_directory" >&2
    exit 73
fi
mkdir -p "$working_directory"
trap 'rm -rf "$working_directory"' EXIT
source_directory="$working_directory/whisper.cpp"
build_directory="$working_directory/build"
stage_directory="$working_directory/stage"
headers_directory="$working_directory/Headers"
archive_name="whisper-v1.9.2-metal-macos.xcframework.zip"

git clone --quiet "$source_repository" "$source_directory"
git -C "$source_directory" checkout --quiet --detach "$WHISPER_COMMIT"
actual_commit=$(git -C "$source_directory" rev-parse HEAD)
if [[ "$actual_commit" != "$WHISPER_COMMIT" ]]; then
    echo "error: expected $WHISPER_COMMIT, got $actual_commit" >&2
    exit 65
fi
git -C "$source_directory" describe --tags --exact-match | grep -Fx "$WHISPER_TAG" >/dev/null
git -C "$source_directory" apply --check "$patch_path"
git -C "$source_directory" apply "$patch_path"

cmake -S "$source_directory" -B "$build_directory" -G Xcode \
    -DCMAKE_OSX_ARCHITECTURES='arm64;x86_64' \
    -DCMAKE_OSX_DEPLOYMENT_TARGET="$DEPLOYMENT_TARGET" \
    -DBUILD_SHARED_LIBS=OFF \
    -DWHISPER_BUILD_EXAMPLES=OFF \
    -DWHISPER_BUILD_SERVER=OFF \
    -DWHISPER_BUILD_TESTS=OFF \
    -DWHISPER_CURL=OFF \
    -DGGML_ACCELERATE=ON \
    -DGGML_BLAS=ON \
    -DGGML_CCACHE=OFF \
    -DGGML_METAL=ON \
    -DGGML_METAL_EMBED_LIBRARY=ON
cmake --build "$build_directory" --config Release --target whisper

embedded_source="$build_directory/ggml/src/ggml-metal/autogenerated/ggml-metal-embed.metal"
if [[ ! -f "$embedded_source" ]]; then
    echo "error: embedded Metal source was not generated" >&2
    exit 70
fi
mkdir -p "$working_directory/metal-module-cache"
xcrun -sdk macosx metal -Werror -DGGML_METAL_EMBED_LIBRARY \
    -fmodules-cache-path="$working_directory/metal-module-cache" \
    -c "$embedded_source" -o "$working_directory/whisper-metal.air"

component_archives=(
    "$build_directory/src/Release/libwhisper.a"
    "$build_directory/ggml/src/Release/libggml.a"
    "$build_directory/ggml/src/Release/libggml-base.a"
    "$build_directory/ggml/src/Release/libggml-cpu.a"
    "$build_directory/ggml/src/ggml-metal/Release/libggml-metal.a"
    "$build_directory/ggml/src/ggml-blas/Release/libggml-blas.a"
)
for archive in "${component_archives[@]}"; do
    if [[ ! -f "$archive" ]]; then
        echo "error: expected component archive not found: $archive" >&2
        exit 70
    fi
done
xcrun libtool -static -D -no_warning_for_no_symbols \
    -o "$working_directory/libwhisper.a" "${component_archives[@]}"

architectures=$(lipo -archs "$working_directory/libwhisper.a")
if [[ "$architectures" != "x86_64 arm64" && "$architectures" != "arm64 x86_64" ]]; then
    echo "error: expected arm64 and x86_64, got: $architectures" >&2
    exit 70
fi

mkdir -p "$headers_directory"
install -m 0644 "$source_directory/include/whisper.h" "$headers_directory/"
for header in ggml.h ggml-alloc.h ggml-backend.h ggml-metal.h ggml-cpu.h ggml-blas.h gguf.h; do
    install -m 0644 "$source_directory/ggml/include/$header" "$headers_directory/"
done
printf '%s\n' \
    'module whisper {' \
    '    header "whisper.h"' \
    '    header "ggml.h"' \
    '    header "ggml-alloc.h"' \
    '    header "ggml-backend.h"' \
    '    header "ggml-metal.h"' \
    '    header "ggml-cpu.h"' \
    '    header "ggml-blas.h"' \
    '    header "gguf.h"' \
    '    link "c++"' \
    '    link framework "Accelerate"' \
    '    link framework "Metal"' \
    '    link framework "Foundation"' \
    '    export *' \
    '}' > "$headers_directory/module.modulemap"

mkdir -p "$stage_directory"
xcodebuild -create-xcframework \
    -library "$working_directory/libwhisper.a" \
    -headers "$headers_directory" \
    -output "$stage_directory/whisper.xcframework"

# Give every archived file the same stable timestamp and omit AppleDouble metadata.
find "$stage_directory/whisper.xcframework" -type f -exec touch -t 202509080000 {} +
mkdir -p "$output_directory"
output_directory=$(cd "$output_directory" && pwd)
(
    cd "$stage_directory"
    COPYFILE_DISABLE=1 LC_ALL=C TZ=UTC find whisper.xcframework -type f -print \
        | LC_ALL=C sort \
        | COPYFILE_DISABLE=1 zip -X -q "$output_directory/$archive_name" -@
)

if unzip -Z1 "$output_directory/$archive_name" | grep -Eq '(^|/)__MACOSX/|(^|/)\._'; then
    echo "error: archive contains macOS metadata" >&2
    exit 70
fi
shasum -a 256 "$output_directory/$archive_name" | tee "$output_directory/$archive_name.sha256"
swift package compute-checksum "$output_directory/$archive_name" \
    | tee "$output_directory/$archive_name.swift-checksum"
printf '%s\n' "$WHISPER_COMMIT" > "$output_directory/whisper.cpp.commit"
xcodebuild -version > "$output_directory/xcode-version.txt"
xcrun metal --version > "$output_directory/metal-version.txt" 2>&1

echo "Built $output_directory/$archive_name"
